import type { LocationRef } from "../types";

/** 14 Kerala districts with HQ / centroid lat-lon for Open-Meteo */
export const KERALA_DISTRICTS: LocationRef[] = [
  {
    id: "tvpm",
    name: "Thiruvananthapuram",
    state: "Kerala",
    district: "Thiruvananthapuram",
    countryCode: "IN",
    lat: 8.5241,
    lon: 76.9366,
  },
  {
    id: "klm",
    name: "Kollam",
    state: "Kerala",
    district: "Kollam",
    countryCode: "IN",
    lat: 8.8932,
    lon: 76.6141,
  },
  {
    id: "pta",
    name: "Pathanamthitta",
    state: "Kerala",
    district: "Pathanamthitta",
    countryCode: "IN",
    lat: 9.2648,
    lon: 76.787,
  },
  {
    id: "alp",
    name: "Alappuzha",
    state: "Kerala",
    district: "Alappuzha",
    countryCode: "IN",
    lat: 9.4981,
    lon: 76.3388,
  },
  {
    id: "ktm",
    name: "Kottayam",
    state: "Kerala",
    district: "Kottayam",
    countryCode: "IN",
    lat: 9.5916,
    lon: 76.5222,
  },
  {
    id: "ekm",
    name: "Ernakulam",
    state: "Kerala",
    district: "Ernakulam",
    countryCode: "IN",
    lat: 9.9816,
    lon: 76.2999,
  },
  {
    id: "idk",
    name: "Idukki",
    state: "Kerala",
    district: "Idukki",
    countryCode: "IN",
    lat: 9.8497,
    lon: 76.9685,
  },
  {
    id: "tsr",
    name: "Thrissur",
    state: "Kerala",
    district: "Thrissur",
    countryCode: "IN",
    lat: 10.5276,
    lon: 76.2144,
  },
  {
    id: "pkd",
    name: "Palakkad",
    state: "Kerala",
    district: "Palakkad",
    countryCode: "IN",
    lat: 10.7867,
    lon: 76.6548,
  },
  {
    id: "mlp",
    name: "Malappuram",
    state: "Kerala",
    district: "Malappuram",
    countryCode: "IN",
    lat: 11.051,
    lon: 76.0711,
  },
  {
    id: "koz",
    name: "Kozhikode",
    state: "Kerala",
    district: "Kozhikode",
    countryCode: "IN",
    lat: 11.2588,
    lon: 75.7804,
  },
  {
    id: "wyd",
    name: "Wayanad",
    state: "Kerala",
    district: "Wayanad",
    countryCode: "IN",
    lat: 11.6854,
    lon: 76.132,
  },
  {
    id: "knr",
    name: "Kannur",
    state: "Kerala",
    district: "Kannur",
    countryCode: "IN",
    lat: 11.8745,
    lon: 75.3704,
  },
  {
    id: "ksgd",
    name: "Kasaragod",
    state: "Kerala",
    district: "Kasaragod",
    countryCode: "IN",
    lat: 12.4996,
    lon: 74.9869,
  },
];

export const DEFAULT_LOCATION_ID = "ekm";

export function getLocationById(id: string): LocationRef | undefined {
  return KERALA_DISTRICTS.find((d) => d.id === id);
}
