import type { LocationRef } from "../types";

/**
 * Major cities outside India for sitemap indexing and search UI quick picks.
 * Coords are Open-Meteo–friendly city centres.
 */
export const WORLD_CITIES: LocationRef[] = [
  // Middle East / Gulf
  { id: "world-dubai", name: "Dubai", state: "Dubai", countryCode: "AE", lat: 25.2048, lon: 55.2708 },
  { id: "world-abu-dhabi", name: "Abu Dhabi", state: "Abu Dhabi", countryCode: "AE", lat: 24.4539, lon: 54.3773 },
  { id: "world-doha", name: "Doha", state: "Doha", countryCode: "QA", lat: 25.2854, lon: 51.531 },
  { id: "world-riyadh", name: "Riyadh", state: "Riyadh", countryCode: "SA", lat: 24.7136, lon: 46.6753 },
  { id: "world-jeddah", name: "Jeddah", state: "Makkah", countryCode: "SA", lat: 21.4858, lon: 39.1925 },
  { id: "world-kuwait-city", name: "Kuwait City", state: "Al Asimah", countryCode: "KW", lat: 29.3759, lon: 47.9774 },
  { id: "world-muscat", name: "Muscat", state: "Muscat", countryCode: "OM", lat: 23.588, lon: 58.3829 },
  { id: "world-manama", name: "Manama", state: "Capital", countryCode: "BH", lat: 26.2235, lon: 50.5876 },
  { id: "world-tehran", name: "Tehran", state: "Tehran", countryCode: "IR", lat: 35.6892, lon: 51.389 },
  { id: "world-baghdad", name: "Baghdad", state: "Baghdad", countryCode: "IQ", lat: 33.3152, lon: 44.3661 },
  { id: "world-amman", name: "Amman", state: "Amman", countryCode: "JO", lat: 31.9454, lon: 35.9284 },
  { id: "world-beirut", name: "Beirut", state: "Beirut", countryCode: "LB", lat: 33.8938, lon: 35.5018 },
  { id: "world-jerusalem", name: "Jerusalem", state: "Jerusalem", countryCode: "IL", lat: 31.7683, lon: 35.2137 },
  { id: "world-tel-aviv", name: "Tel Aviv", state: "Tel Aviv", countryCode: "IL", lat: 32.0853, lon: 34.7818 },
  // South Asia
  { id: "world-colombo", name: "Colombo", state: "Western", countryCode: "LK", lat: 6.9271, lon: 79.8612 },
  { id: "world-kathmandu", name: "Kathmandu", state: "Bagmati", countryCode: "NP", lat: 27.7172, lon: 85.324 },
  { id: "world-dhaka", name: "Dhaka", state: "Dhaka", countryCode: "BD", lat: 23.8103, lon: 90.4125 },
  { id: "world-chittagong", name: "Chittagong", state: "Chittagong", countryCode: "BD", lat: 22.3569, lon: 91.7832 },
  { id: "world-karachi", name: "Karachi", state: "Sindh", countryCode: "PK", lat: 24.8607, lon: 67.0011 },
  { id: "world-lahore", name: "Lahore", state: "Punjab", countryCode: "PK", lat: 31.5204, lon: 74.3587 },
  { id: "world-islamabad", name: "Islamabad", state: "Islamabad", countryCode: "PK", lat: 33.6844, lon: 73.0479 },
  { id: "world-male", name: "Malé", state: "Kaafu", countryCode: "MV", lat: 4.1755, lon: 73.5093 },
  // Southeast Asia
  { id: "world-singapore", name: "Singapore", state: "Singapore", countryCode: "SG", lat: 1.3521, lon: 103.8198 },
  { id: "world-bangkok", name: "Bangkok", state: "Bangkok", countryCode: "TH", lat: 13.7563, lon: 100.5018 },
  { id: "world-kuala-lumpur", name: "Kuala Lumpur", state: "Kuala Lumpur", countryCode: "MY", lat: 3.139, lon: 101.6869 },
  { id: "world-jakarta", name: "Jakarta", state: "Jakarta", countryCode: "ID", lat: -6.2088, lon: 106.8456 },
  { id: "world-bali", name: "Denpasar", state: "Bali", countryCode: "ID", lat: -8.6705, lon: 115.2126 },
  { id: "world-manila", name: "Manila", state: "Metro Manila", countryCode: "PH", lat: 14.5995, lon: 120.9842 },
  { id: "world-hanoi", name: "Hanoi", state: "Hanoi", countryCode: "VN", lat: 21.0278, lon: 105.8342 },
  { id: "world-ho-chi-minh", name: "Ho Chi Minh City", state: "Ho Chi Minh", countryCode: "VN", lat: 10.8231, lon: 106.6297 },
  { id: "world-phnom-penh", name: "Phnom Penh", state: "Phnom Penh", countryCode: "KH", lat: 11.5564, lon: 104.9282 },
  { id: "world-yangon", name: "Yangon", state: "Yangon", countryCode: "MM", lat: 16.8409, lon: 96.1735 },
  // East Asia
  { id: "world-tokyo", name: "Tokyo", state: "Tokyo", countryCode: "JP", lat: 35.6762, lon: 139.6503 },
  { id: "world-osaka", name: "Osaka", state: "Osaka", countryCode: "JP", lat: 34.6937, lon: 135.5023 },
  { id: "world-seoul", name: "Seoul", state: "Seoul", countryCode: "KR", lat: 37.5665, lon: 126.978 },
  { id: "world-busan", name: "Busan", state: "Busan", countryCode: "KR", lat: 35.1796, lon: 129.0756 },
  { id: "world-beijing", name: "Beijing", state: "Beijing", countryCode: "CN", lat: 39.9042, lon: 116.4074 },
  { id: "world-shanghai", name: "Shanghai", state: "Shanghai", countryCode: "CN", lat: 31.2304, lon: 121.4737 },
  { id: "world-hong-kong", name: "Hong Kong", state: "Hong Kong", countryCode: "HK", lat: 22.3193, lon: 114.1694 },
  { id: "world-taipei", name: "Taipei", state: "Taipei", countryCode: "TW", lat: 25.033, lon: 121.5654 },
  // Europe
  { id: "world-london", name: "London", state: "England", countryCode: "GB", lat: 51.5072, lon: -0.1276 },
  { id: "world-manchester", name: "Manchester", state: "England", countryCode: "GB", lat: 53.4808, lon: -2.2426 },
  { id: "world-edinburgh", name: "Edinburgh", state: "Scotland", countryCode: "GB", lat: 55.9533, lon: -3.1883 },
  { id: "world-paris", name: "Paris", state: "Île-de-France", countryCode: "FR", lat: 48.8566, lon: 2.3522 },
  { id: "world-lyon", name: "Lyon", state: "Auvergne-Rhône-Alpes", countryCode: "FR", lat: 45.764, lon: 4.8357 },
  { id: "world-berlin", name: "Berlin", state: "Berlin", countryCode: "DE", lat: 52.52, lon: 13.405 },
  { id: "world-munich", name: "Munich", state: "Bavaria", countryCode: "DE", lat: 48.1351, lon: 11.582 },
  { id: "world-frankfurt", name: "Frankfurt", state: "Hesse", countryCode: "DE", lat: 50.1109, lon: 8.6821 },
  { id: "world-amsterdam", name: "Amsterdam", state: "North Holland", countryCode: "NL", lat: 52.3676, lon: 4.9041 },
  { id: "world-brussels", name: "Brussels", state: "Brussels", countryCode: "BE", lat: 50.8503, lon: 4.3517 },
  { id: "world-zurich", name: "Zurich", state: "Zurich", countryCode: "CH", lat: 47.3769, lon: 8.5417 },
  { id: "world-geneva", name: "Geneva", state: "Geneva", countryCode: "CH", lat: 46.2044, lon: 6.1432 },
  { id: "world-vienna", name: "Vienna", state: "Vienna", countryCode: "AT", lat: 48.2082, lon: 16.3738 },
  { id: "world-rome", name: "Rome", state: "Lazio", countryCode: "IT", lat: 41.9028, lon: 12.4964 },
  { id: "world-milan", name: "Milan", state: "Lombardy", countryCode: "IT", lat: 45.4642, lon: 9.19 },
  { id: "world-madrid", name: "Madrid", state: "Madrid", countryCode: "ES", lat: 40.4168, lon: -3.7038 },
  { id: "world-barcelona", name: "Barcelona", state: "Catalonia", countryCode: "ES", lat: 41.3874, lon: 2.1686 },
  { id: "world-lisbon", name: "Lisbon", state: "Lisbon", countryCode: "PT", lat: 38.7223, lon: -9.1393 },
  { id: "world-dublin", name: "Dublin", state: "Leinster", countryCode: "IE", lat: 53.3498, lon: -6.2603 },
  { id: "world-stockholm", name: "Stockholm", state: "Stockholm", countryCode: "SE", lat: 59.3293, lon: 18.0686 },
  { id: "world-oslo", name: "Oslo", state: "Oslo", countryCode: "NO", lat: 59.9139, lon: 10.7522 },
  { id: "world-copenhagen", name: "Copenhagen", state: "Capital", countryCode: "DK", lat: 55.6761, lon: 12.5683 },
  { id: "world-helsinki", name: "Helsinki", state: "Uusimaa", countryCode: "FI", lat: 60.1699, lon: 24.9384 },
  { id: "world-warsaw", name: "Warsaw", state: "Masovian", countryCode: "PL", lat: 52.2297, lon: 21.0122 },
  { id: "world-prague", name: "Prague", state: "Prague", countryCode: "CZ", lat: 50.0755, lon: 14.4378 },
  { id: "world-budapest", name: "Budapest", state: "Budapest", countryCode: "HU", lat: 47.4979, lon: 19.0402 },
  { id: "world-athens", name: "Athens", state: "Attica", countryCode: "GR", lat: 37.9838, lon: 23.7275 },
  { id: "world-istanbul", name: "Istanbul", state: "Istanbul", countryCode: "TR", lat: 41.0082, lon: 28.9784 },
  { id: "world-ankara", name: "Ankara", state: "Ankara", countryCode: "TR", lat: 39.9334, lon: 32.8597 },
  { id: "world-moscow", name: "Moscow", state: "Moscow", countryCode: "RU", lat: 55.7558, lon: 37.6173 },
  { id: "world-saint-petersburg", name: "Saint Petersburg", state: "Saint Petersburg", countryCode: "RU", lat: 59.9311, lon: 30.3609 },
  // Africa
  { id: "world-cairo", name: "Cairo", state: "Cairo", countryCode: "EG", lat: 30.0444, lon: 31.2357 },
  { id: "world-alexandria", name: "Alexandria", state: "Alexandria", countryCode: "EG", lat: 31.2001, lon: 29.9187 },
  { id: "world-lagos", name: "Lagos", state: "Lagos", countryCode: "NG", lat: 6.5244, lon: 3.3792 },
  { id: "world-nairobi", name: "Nairobi", state: "Nairobi", countryCode: "KE", lat: -1.2921, lon: 36.8219 },
  { id: "world-johannesburg", name: "Johannesburg", state: "Gauteng", countryCode: "ZA", lat: -26.2041, lon: 28.0473 },
  { id: "world-cape-town", name: "Cape Town", state: "Western Cape", countryCode: "ZA", lat: -33.9249, lon: 18.4241 },
  { id: "world-casablanca", name: "Casablanca", state: "Casablanca-Settat", countryCode: "MA", lat: 33.5731, lon: -7.5898 },
  { id: "world-addis-ababa", name: "Addis Ababa", state: "Addis Ababa", countryCode: "ET", lat: 9.032, lon: 38.7469 },
  { id: "world-accra", name: "Accra", state: "Greater Accra", countryCode: "GH", lat: 5.6037, lon: -0.187 },
  // Americas
  { id: "world-newyork", name: "New York", state: "New York", countryCode: "US", lat: 40.7128, lon: -74.006 },
  { id: "world-los-angeles", name: "Los Angeles", state: "California", countryCode: "US", lat: 34.0522, lon: -118.2437 },
  { id: "world-chicago", name: "Chicago", state: "Illinois", countryCode: "US", lat: 41.8781, lon: -87.6298 },
  { id: "world-houston", name: "Houston", state: "Texas", countryCode: "US", lat: 29.7604, lon: -95.3698 },
  { id: "world-san-francisco", name: "San Francisco", state: "California", countryCode: "US", lat: 37.7749, lon: -122.4194 },
  { id: "world-seattle", name: "Seattle", state: "Washington", countryCode: "US", lat: 47.6062, lon: -122.3321 },
  { id: "world-miami", name: "Miami", state: "Florida", countryCode: "US", lat: 25.7617, lon: -80.1918 },
  { id: "world-washington", name: "Washington", state: "District of Columbia", countryCode: "US", lat: 38.9072, lon: -77.0369 },
  { id: "world-boston", name: "Boston", state: "Massachusetts", countryCode: "US", lat: 42.3601, lon: -71.0589 },
  { id: "world-toronto", name: "Toronto", state: "Ontario", countryCode: "CA", lat: 43.6532, lon: -79.3832 },
  { id: "world-vancouver", name: "Vancouver", state: "British Columbia", countryCode: "CA", lat: 49.2827, lon: -123.1207 },
  { id: "world-montreal", name: "Montreal", state: "Quebec", countryCode: "CA", lat: 45.5017, lon: -73.5673 },
  { id: "world-mexico-city", name: "Mexico City", state: "CDMX", countryCode: "MX", lat: 19.4326, lon: -99.1332 },
  { id: "world-sao-paulo", name: "São Paulo", state: "São Paulo", countryCode: "BR", lat: -23.5505, lon: -46.6333 },
  { id: "world-rio", name: "Rio de Janeiro", state: "Rio de Janeiro", countryCode: "BR", lat: -22.9068, lon: -43.1729 },
  { id: "world-buenos-aires", name: "Buenos Aires", state: "Buenos Aires", countryCode: "AR", lat: -34.6037, lon: -58.3816 },
  { id: "world-santiago", name: "Santiago", state: "Santiago", countryCode: "CL", lat: -33.4489, lon: -70.6693 },
  { id: "world-lima", name: "Lima", state: "Lima", countryCode: "PE", lat: -12.0464, lon: -77.0428 },
  { id: "world-bogota", name: "Bogotá", state: "Bogotá", countryCode: "CO", lat: 4.711, lon: -74.0721 },
  // Oceania
  { id: "world-sydney", name: "Sydney", state: "NSW", countryCode: "AU", lat: -33.8688, lon: 151.2093 },
  { id: "world-melbourne", name: "Melbourne", state: "Victoria", countryCode: "AU", lat: -37.8136, lon: 144.9631 },
  { id: "world-brisbane", name: "Brisbane", state: "Queensland", countryCode: "AU", lat: -27.4698, lon: 153.0251 },
  { id: "world-perth", name: "Perth", state: "Western Australia", countryCode: "AU", lat: -31.9505, lon: 115.8605 },
  { id: "world-auckland", name: "Auckland", state: "Auckland", countryCode: "NZ", lat: -36.8485, lon: 174.7633 },
  { id: "world-wellington", name: "Wellington", state: "Wellington", countryCode: "NZ", lat: -41.2865, lon: 174.7762 },
];

/** Shown in the empty-state search panel (subset of WORLD_CITIES + Mumbai). */
export const WORLD_QUICK_PICKS: LocationRef[] = [
  WORLD_CITIES.find((c) => c.id === "world-dubai")!,
  WORLD_CITIES.find((c) => c.id === "world-singapore")!,
  WORLD_CITIES.find((c) => c.id === "world-london")!,
  WORLD_CITIES.find((c) => c.id === "world-newyork")!,
  WORLD_CITIES.find((c) => c.id === "world-tokyo")!,
  WORLD_CITIES.find((c) => c.id === "world-sydney")!,
  WORLD_CITIES.find((c) => c.id === "world-berlin")!,
  WORLD_CITIES.find((c) => c.id === "world-toronto")!,
  WORLD_CITIES.find((c) => c.id === "world-paris")!,
  {
    id: "in-mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    countryCode: "IN",
    lat: 19.076,
    lon: 72.8777,
  },
];
